spring:
  datasource:
    url: jdbc:mysql://localhost:3306/keepnote02?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    
  application:
    name: authentication-service
    
server:
  port: 9100

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka