spring:
  datasource:
    url: jdbc:mysql://localhost:3306/keepnote05?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: user-service
server:
  port: 9200
  
#eureka:
 # client:
  #  service-url:
   #   default-zone: http://localhost:8761/eureka



