spring:
  data:
    mongodb:
     database: keepnote
     port: 27017
     host: localhost
  application:
    name: note-service
server:
  port: 9300

  
#eureka:
 # client:
  #  service-url:
   #   default-zone: http://localhost:8761/eureka